
on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install
        
      - name: Build web app
        run: ionic build --prod

      - name: Sync Android platform
        run: ionic capacitor sync android
        
      - name: Build Android Dev APK
        working-directory: ./android/
        run: ./gradlew assembleDebug && ./gradlew installDebug

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: android/app/build/outputs/apk/debug/app-debug.apk
